FROM quay-proxy.ci.openshift.org/openshift/ci:ocp_builder_rhel-9-golang-1.24-openshift-4.20 AS builder
WORKDIR /go/src/github.com/openshift/csi-operator
COPY . .
RUN make GO_BUILD_PACKAGES=./cmd/aws-efs-csi-driver-operator

FROM quay-proxy.ci.openshift.org/openshift/ci:ocp_4.20_base-rhel9
COPY --from=builder /go/src/github.com/openshift/csi-operator/bin/aws-efs-csi-driver-operator /usr/bin/
ENTRYPOINT ["/usr/bin/aws-efs-csi-driver-operator"]
LABEL io.k8s.display-name="OpenShift AWS EFS CSI Driver Operator" \
	io.k8s.description="The AWS EFS CSI Driver Operator installs and maintains the AWS EFS CSI Driver on a cluster."
